parserOptions:
  ecmaVersion: 6
  sourceType: module

env:
  node: true
  es6: true

root: true

extends: pedant

rules:
  valid-jsdoc:
    - 2
    -
      requireParamDescription: false
      requireReturnDescription: false
